name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: install dev
      run: cd frontend && npm ci

    - name: jest
      run: make test
      
    - name: Publish code coverage on Code Climate
      uses: paambaati/codeclimate-action@v3.2.0
      
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
          coverageCommand: make test-coverage
          debug: true
