name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dev
      run: make install

    - name: jest
      run: make test
      
    - name: Publish code coverage on Code Climate
      uses: paambaati/codeclimate-action@v5.0.0
      
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        JACOCO_SOURCE_PATH: frontend
      with:
          coverageCommand: make test-coverage
          debug: true
